### ISSUE TITLE
How about CLI?

### ISSUE THREAD

**Issue by anqur** [giantbranch/moveDecrypt#1]
各旋转结果使用 CLI 界面展示也是挺方便的
- 在 GNU/Linux 及 BSD 各发行版普遍提供 `bsdgames` 这个包, 内置
  - `caesar`, 提供基本的旋转, 甚至有根据 **频率** 来简单解码的算法
  - `rot13`, 提供旋转 13 位算法的快捷命令
- 以此为基础, 用 Shell 脚本很容易写好主逻辑, 再加上绘制 CLI 界面即可, 多线程貌似都不必要

**Comment by giantbranch** [comment]
上年写的，更新上去而已........
